services:
  - type: web
    name: terabox-telegram-bot
    runtime: node
    buildCommand: npm install
    startCommand: ./start.sh
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
